// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVN4uYBoy1XOdLp7b5a0aC9zg0Ud-yn44',
    appId: '1:363580058617:web:197d2fea31f781652f2b28',
    messagingSenderId: '363580058617',
    projectId: 'cam-balkon-analiz',
    authDomain: 'cam-balkon-analiz.firebaseapp.com',
    databaseURL: 'https://cam-balkon-analiz.firebaseio.com',
    storageBucket: 'cam-balkon-analiz.appspot.com',
    measurementId: 'G-GD2GJQBFHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKIycKY6szpMuwfBMPPc1X_sY32QmrzOc',
    appId: '1:363580058617:android:cba98107d4c530e32f2b28',
    messagingSenderId: '363580058617',
    projectId: 'cam-balkon-analiz',
    databaseURL: 'https://cam-balkon-analiz.firebaseio.com',
    storageBucket: 'cam-balkon-analiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPDvXSENYI4Td4U0vmYEgBa5saxCSnoI',
    appId: '1:363580058617:ios:f9280176c73417c32f2b28',
    messagingSenderId: '363580058617',
    projectId: 'cam-balkon-analiz',
    databaseURL: 'https://cam-balkon-analiz.firebaseio.com',
    storageBucket: 'cam-balkon-analiz.appspot.com',
    androidClientId: '363580058617-33l5jgvlubju6r3e2t90at6boop0a53t.apps.googleusercontent.com',
    iosClientId: '363580058617-i490jbougsonanf42edi29gsl6i1cnsl.apps.googleusercontent.com',
    iosBundleId: 'com.kurt.glassbalcony.glassbalconyanalysis',
  );
}
